### ISSUE TITLE
Doesn't work with i18n-webpack-plugin

### ISSUE THREAD

**Issue by syuilo** [riot/tag-loader#5] opened 2017-03-22 16:48 UTC
It seems doesn't work with [i18n-webpack-plugin](https://github.com/webpack-contrib/i18n-webpack-plugin).

Code:
``` html
<my-tag>
  <p>{ __('my-text') }</p>
</my-tag>
```

Got:
```
__ is not a function
```

That is, the expression in the tag does not seem to be parsed by webpack.

So, the following code works **(but this is redundant!)**:
``` html
<my-tag>
  <p>{ myText }</p>
  <script>
    this.myText = __('my-text')
  </script>
</my-tag>
```

Any solutions?
Is riot-tag-loader able to pass expressions in tags to webpack?

thanks.

**Comment by GianlucaGuarini** [comment] 2017-12-28 20:48
could you please reproduce the issue in a repo? In the mean time i will close this issue because i can't reproduce it

**Closed by GianlucaGuarini** 2017-12-28 20:48 UTC
Labels: question
